@base_url = http://localhost:8200/api/admin

GET {{base_url}}/products

###

GET {{base_url}}/product/1

###

PUT {{base_url}}/product/1
Content-Type: application/json

{
  "productID": 1,
  "name": "Kayak",
  "description": "A boat for one person",
  "price": 275.80,
  "category": "Watersports"
}

###

DELETE {{base_url}}/product/4

###

POST {{base_url}}/product-seed
Content-Type: application/json

###